#Name
CONFIG_ZMK_KEYBOARD_NAME="Pad Pocket Trio v1.0"

# RGB Underglow
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=y
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=205
CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=0
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=25
CONFIG_ZMK_RGB_UNDERGLOW_SPD_START=3
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=0

#Power
CONFIG_ZMK_EXT_POWER=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y

#Memory
CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=5184000000
# CONFIG_ZMK_SETTINGS_RESET_ON_START=y
# CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=10

#Scroll Options
CONFIG_ZMK_POINTING=y

# Increase bluetooth power transmit
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_SLEEP=n
CONFIG_ZMK_PM_SOFT_OFF=n

# Bluetooth Options
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y

# ZMK Studio
CONFIG_ZMK_STUDIO=y